<a href="https://colab.research.google.com/github/shivanshi2206/BIG_DATA_ANALYTICS/blob/main/assignment2_202301061.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


Q1

In [ ]:
 a=np.array([1, 2, 3, 6, 4, 5])

In [ ]:
r_a=a[::-1]
r_a

array([5, 4, 6, 3, 2, 1])

Q2

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [ ]:
b=np.array_equal(arr1,arr2)
b

True

In [ ]:
arr3 = np.array([[1, 2,1], [3, 4,0]])
arr4 = np.array([[1, 2], [3, 4]])
c=np.array_equal(arr3,arr4)

In [ ]:
c

False

Q3

In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1,0])
unique_values,count=np.unique(x,return_counts=True)

print("Unique values:", unique_values)
print("Counts:", count)



Unique values: [0 1 2 3 4 5]
Counts: [1 5 2 1 1 1]


Q4

In [ ]:
g= np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum_g=np.sum(g)
sum_g_row=np.sum(g,axis=1)
sum_g_col=np.sum(g,axis=0)
sum_g_col, sum_g_row, sum_g


(matrix([[20,  9, 16]]),
 matrix([[14],
         [16],
         [15]]),
 45)